name: PR Preprod
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - preprod

jobs:
  build:
    name: Perform checks and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs Yarn globally
        run: npm install -g yarn
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn global add serve  # server for production build

        ###############################################################
        #                   Type check & code style                   #
        ###############################################################
      - name: Type check & code style (tslint)
        run: yarn type-check && yarn lint

      - name: Do nextJs cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

        ###############################################################
        #                        Build project                        #
        ###############################################################
      - name: Build production env
        run: yarn build

        ###############################################################
        #                          Run tests                          #
        ###############################################################
      - name: Run unit tests
        run: yarn tests:unit:cov
