# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  debug:
    # The type of runner that the job will run on
    name: Debug
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up secret file
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ github.token }} | sed 's/./& /g'
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
